import Foundation

struct RunningPhrase {
    let es: String
    let en: String  // TODO: fill when localizing to English
}

extension RunningPhrase {
    // swiftlint:disable line_length
    static let all: [RunningPhrase] = [
        .init(es: "Sal a correr. Tus excusas ya están en forma, tú no.", en: ""),
        .init(es: "La cama no te va a extrañar tanto como crees.", en: ""),
        .init(es: "Tus tenis están polvorientos. Eso dice todo.", en: ""),
        .init(es: "Correr duele. Quedarse quieto para siempre también.", en: ""),
        .init(es: "Un km. Ni siquiera tu abuela lo discutiría.", en: ""),
        .init(es: "Tu yo de mañana va a odiarte menos si sales hoy.", en: ""),
        .init(es: "Vitamina D: viene en kilómetros, no en cápsulas.", en: ""),
        .init(es: "Cada paso cuenta. Incluso el que diste al refri.", en: ""),
        .init(es: "El sofá te quiere. Tus arterias, no tanto.", en: ""),
        .init(es: "Correr es gratis. El cardiólogo, no.", en: ""),
        .init(es: "Hoy es un buen día para no arrepentirte mañana.", en: ""),
        .init(es: "Tu mascota necesita energía. Tú necesitas menos excusas.", en: ""),
        .init(es: "Nadie se arrepintió de un día que salió a correr.", en: ""),
        .init(es: "El clima nunca va a ser perfecto. Sal de todas formas.", en: ""),
        .init(es: "Corre lento si quieres, pero corre.", en: ""),
        .init(es: "Tu cuerpo puede más de lo que tu cabeza admite.", en: ""),
        .init(es: "El peor run es el que no hiciste.", en: ""),
        .init(es: "Sal afuera. Netflix sigue ahí cuando regreses.", en: ""),
        .init(es: "Correr 1km quema vergüenza y calorías, en ese orden.", en: ""),
        .init(es: "Tus músculos no crecen en el sillón. Dato curioso.", en: ""),
        .init(es: "El tiempo pasa igual corras o no. Mejor corriendo.", en: ""),
        .init(es: "No necesitas motivación, necesitas tenis y la puerta.", en: ""),
        .init(es: "Hoy es el 'mañana' que postergaste ayer.", en: ""),
        .init(es: "El sudor es solo grasa llorando. Dale más razones.", en: ""),
        .init(es: "Sal a correr antes de que tu cerebro invente más excusas.", en: ""),
        .init(es: "Un run malo sigue siendo mejor que ningún run.", en: ""),
        .init(es: "Tu mascota corre contigo. Literalmente. No la defraudes.", en: ""),
        .init(es: "Cada km es una apuesta a tu yo de 10 años.", en: ""),
        .init(es: "Hoy decides: sillón o tenis.", en: ""),
        .init(es: "El oxígeno extra también le hace bien a tus ideas.", en: ""),
        .init(es: "Los tenis no se van a poner solos. Esperemos que no.", en: ""),
        .init(es: "Dale play a tu playlist y para de pensar.", en: ""),
        .init(es: "La ciudad se ve diferente desde las piernas.", en: ""),
        .init(es: "Tu mascota te mira. No la decepciones.", en: ""),
        .init(es: "El run más difícil es el primer paso fuera de la puerta.", en: ""),
        .init(es: "Hoy no es día de descanso si ayer tampoco corriste.", en: ""),
        .init(es: "La motivación viene después de empezar, no antes.", en: ""),
        .init(es: "Corre suficiente para que el helado de después valga.", en: ""),
        .init(es: "Afuera hay aire fresco. Adentro hay pretextos.", en: ""),
        .init(es: "Si corriste, ganaste. Así de simple.", en: ""),
        .init(es: "Tu corazón quiere latir fuerte por las razones correctas.", en: ""),
        .init(es: "1km es 1km más que ayer. Matemáticas brutales.", en: ""),
        .init(es: "Tus rodillas ahorita: quejándose. En 10 años: agradecidas.", en: ""),
        .init(es: "Sal a correr. La ansiedad prefiere cuerpos quietos.", en: ""),
        .init(es: "Corre antes de que el día te gane la partida.", en: ""),
        .init(es: "No necesitas correr rápido, necesitas correr.", en: ""),
        .init(es: "Tu mascota tiene más energía cuando tú corres. Nota mental.", en: ""),
        .init(es: "El mundo no se acaba, pero tu día sí. Sal.", en: ""),
        .init(es: "Cada kilómetro le dice a tu cuerpo: todavía puedo.", en: ""),
        .init(es: "Tus excusas son muy creativas. Tus piernas también pueden.", en: ""),
        .init(es: "Corre despacio si quieres. El ritmo es tuyo, los km también.", en: ""),
        .init(es: "Los 66 días no se hacen solos. Empieza con uno.", en: ""),
        .init(es: "Hoy es día 1. O día 23. O 47. Sal de todas formas.", en: ""),
        .init(es: "Los audífonos y los tenis son el par perfecto.", en: ""),
        .init(es: "Hay un run ahí afuera con tu nombre. Ve por él.", en: ""),
        .init(es: "Tu mascota no te juzga el ritmo. Solo quiere que salgas.", en: ""),
        .init(es: "Corre. Porque estar vivo merece celebrarse en kilómetros.", en: ""),
        .init(es: "Tus pulmones mejoran usándolos. Como casi todo.", en: ""),
        .init(es: "El sol salió antes que tú. No lo hagas quedar mal.", en: ""),
        .init(es: "Un run = un día de orgullo. Las cuentas dan.", en: ""),
        .init(es: "Tu cuerpo quiere moverse. Tu cerebro tiene miedo al esfuerzo.", en: ""),
        .init(es: "La pereza es temporal. El hábito es para siempre.", en: ""),
        .init(es: "La mejor versión de ti ya está poniéndose los tenis.", en: ""),
        .init(es: "Corre aunque no quieras. Especialmente si no quieres.", en: ""),
        .init(es: "El kilómetro más honesto es siempre el primero.", en: ""),
        .init(es: "Afuera hace frío. Adentro hace cómodo. Sal de todas formas.", en: ""),
        .init(es: "Tu mascota se alegra cada vez que corres. No es coincidencia.", en: ""),
        .init(es: "Correr es lo más barato que puedes hacer por tu salud.", en: ""),
        .init(es: "No se trata de velocidad, se trata de aparecer.", en: ""),
        .init(es: "El asfalto está esperando tus pasos. O tus excusas. Tú decides.", en: ""),
        .init(es: "Cada run malo construye el run bueno que sigue.", en: ""),
        .init(es: "Tus pies saben el camino. Tu cabeza solo pone obstáculos.", en: ""),
        .init(es: "El run perfecto no existe. El run de hoy, sí.", en: ""),
        .init(es: "Correr es el único deporte donde siempre ganas contra ti.", en: ""),
        .init(es: "Hoy no es el día de echarte para atrás.", en: ""),
        .init(es: "Tus tenis no están decorando tu cuarto. Están esperando.", en: ""),
        .init(es: "Tu mente necesita kilómetros más que café. A veces.", en: ""),
        .init(es: "Un run al día mantiene la queja al margen.", en: ""),
        .init(es: "Corre aunque solo sea para contarlo después.", en: ""),
        .init(es: "El mejor momento para correr fue ayer. El segundo es ahora.", en: ""),
        .init(es: "Tu mascota cuenta cada km. No la hagas esperar.", en: ""),
        .init(es: "No mañana. Hoy. Ahora. Ya. ¿Qué estás esperando?", en: ""),
        .init(es: "Sal. Tu versión sedentaria no tiene voto en esto.", en: ""),
        .init(es: "Corre. Porque las endorfinas son felicidad de farmacia, gratis.", en: ""),
        .init(es: "El gym puede esperar. El hábito de 66 días, no tanto.", en: ""),
        .init(es: "Incluso los lentos llegan. Un km a la vez.", en: ""),
        .init(es: "Sal. Tu yo del futuro ya tiene los tenis puestos.", en: ""),
        .init(es: "Corre. Tus problemas no pueden alcanzarte... bueno, pero sudas.", en: ""),
        .init(es: "La cama es cómoda. También lo es rendirse. Piénsalo.", en: ""),
        .init(es: "Tu colesterol no se baja viendo el partido. Dato.", en: ""),
        .init(es: "Sal. Hay endorfinas ahí afuera y son completamente legales.", en: ""),
        .init(es: "Corre. Porque sí. Porque puedes. Porque ¿por qué no?", en: ""),
        .init(es: "Hoy no es el día de negociar con tu sillón.", en: ""),
        .init(es: "Los 66 días se construyen uno a la vez. Este es el tuyo.", en: ""),
        .init(es: "Sal afuera. Tu mascota ya tiene las patas listas.", en: ""),
        .init(es: "Corre. Tu corazón te lo va a agradecer. Tu Netflix, no.", en: ""),
        .init(es: "El run de hoy es la energía de mañana. Y pasado.", en: ""),
        .init(es: "Sal. La ciudad tiene un camino con tu nombre grabado.", en: ""),
        .init(es: "Corre aunque la playlist no esté en su mejor canción.", en: ""),
        .init(es: "Hoy no te pido un maratón. Solo que salgas.", en: ""),
        .init(es: "El hábito que buscas está del otro lado de la puerta.", en: ""),
        .init(es: "Tu cuerpo ya sabe cómo correr. Tu cerebro solo exagera.", en: ""),
        .init(es: "Dale a tus pulmones algo de qué presumir.", en: ""),
        .init(es: "La versión floja de ti también quiere salir. No le hagas caso.", en: ""),
        .init(es: "Tus piernas tienen más kilómetros disponibles. Úsalos.", en: ""),
        .init(es: "El piso no se va a mover solo. Muévete tú.", en: ""),
        .init(es: "Nadie en la historia lamentó haberse levantado a correr.", en: ""),
        .init(es: "Hoy tu mascota tiene hambre de kilómetros. Aliméntala.", en: ""),
        .init(es: "El viento en la cara no cuesta nada. Sal a sentirlo.", en: ""),
        .init(es: "Correr es el único momento del día donde nadie te molesta.", en: ""),
        .init(es: "Tu mente se reinicia con kilómetros, no con pantallas.", en: ""),
        .init(es: "Mueve el cuerpo antes de que el día te mueva a ti.", en: ""),
        .init(es: "Hay un run esperándote. Puntual, calladito, sin excusas.", en: ""),
        .init(es: "Sal aunque no estés de humor. El humor llega al segundo km.", en: ""),
        .init(es: "El mundo se ve más pequeño desde las piernas cansadas.", en: ""),
        .init(es: "Tu corazón late gratis. Hazlo latir por algo.", en: ""),
        .init(es: "No hace falta correr lejos. Solo hace falta correr.", en: ""),
        .init(es: "Hoy el sofá pierde. Sal.", en: ""),
        .init(es: "Una vuelta a la manzana también es un run. Te cuento.", en: ""),
        .init(es: "El camino más corto al bienestar lleva tenis.", en: ""),
        .init(es: "Si esperas que llueva para no salir, se llama excusa disfrazada.", en: ""),
        .init(es: "Tu mascota no tiene días malos cuando corren juntos.", en: ""),
        .init(es: "Corre. Tu cerebro lo necesita más de lo que admite.", en: ""),
        .init(es: "Hoy es el día que cambia el contador. Sal.", en: ""),
        .init(es: "Tus pies tienen memoria. Enséñales el camino correcto.", en: ""),
        .init(es: "La queja no quema calorías. El run sí.", en: ""),
        .init(es: "No se trata de ser rápido. Se trata de no parar.", en: ""),
        .init(es: "El dolor de correr dura horas. El orgullo, días.", en: ""),
        .init(es: "Sal. La ciudad te tiene preparada una ruta sin cobrar.", en: ""),
        .init(es: "Tu cuerpo es el único vehiculo que no puedes cambiar. Mantenlo.", en: ""),
        .init(es: "Corre antes de que el desayuno tome partido por el sillón.", en: ""),
        .init(es: "Los 66 días te necesitan a ti, no al gimnasio.", en: ""),
        .init(es: "Cinco minutos trotando ya cambiaron tu día. Pruébalo.", en: ""),
        .init(es: "Tu mascota no entiende de descanso activo. Solo de correr.", en: ""),
        .init(es: "Hoy no. Claro que no. Pero sal de todas formas.", en: ""),
        .init(es: "El sudor es el idioma que hablan tus metas.", en: ""),
        .init(es: "No necesitas estar listo. Necesitas estar afuera.", en: ""),
        .init(es: "Hay un km ahí afuera que ya tiene tu nombre. Reclámalo.", en: ""),
        .init(es: "Tu mood mejora con movimiento. Dato no tan curioso.", en: ""),
        .init(es: "Corre por las razones incorrectas si quieres. Igual cuenta.", en: ""),
        .init(es: "El mejor run es el que nadie más puede hacer por ti.", en: ""),
        .init(es: "Sal. Tu versión sedentaria ya habló bastante hoy.", en: ""),
        .init(es: "Un solo run puede salvar un día completo. Intento probado.", en: ""),
        .init(es: "El mundo tiene kilómetros gratis. No los desperdicies.", en: ""),
        .init(es: "Tu mascota lleva la cuenta. Hoy le debes uno.", en: ""),
        .init(es: "Sal aunque solo sean 15 minutos. El hábito no negocia.", en: ""),
        .init(es: "Tus arterias se merecen un poco de esfuerzo hoy.", en: ""),
        .init(es: "El run que menos ganas tienes es el que más necesitas.", en: ""),
        .init(es: "Corre. Después puedes comer lo que quieras. Más o menos.", en: ""),
        .init(es: "El asfalto no juzga tu ritmo. Solo tus pies.", en: ""),
        .init(es: "Hoy es uno de los 66. No lo desperdicies.", en: ""),
        .init(es: "Tu energía no se agota corriendo, se multiplica.", en: ""),
        .init(es: "Corre aunque tu cuerpo diga que no. Especialmente entonces.", en: ""),
        .init(es: "El tiempo pasa igual. Mejor que te encuentre en movimiento.", en: ""),
        .init(es: "No hay run perfecto. Hay run de hoy. Ese alcanza.", en: ""),
        .init(es: "Sal. Tu mascota ya se puso los tenis imaginarios.", en: ""),
        .init(es: "Un run malo te pone en mejor forma que ningún run.", en: ""),
        .init(es: "Hoy no tienes excusa nueva. Ya las usaste todas.", en: ""),
        .init(es: "Tus pulmones ensanchan con uso. No guardes el empaque.", en: ""),
        .init(es: "El primer km siempre miente. Después se pone bueno.", en: ""),
        .init(es: "Sal a que el aire te limpie la cabeza.", en: ""),
        .init(es: "Tu cuerpo es el proyecto más importante que tienes.", en: ""),
        .init(es: "Corre para ti. No para la app. Pero la app también lo registra.", en: ""),
        .init(es: "El mejor antidepresivo tiene cordones y suela de goma.", en: ""),
        .init(es: "Hoy es el día 1 de alguien. Que sea el tuyo también.", en: ""),
        .init(es: "No necesitas un plan. Necesitas salir por la puerta.", en: ""),
        .init(es: "Tu mascota envejece más lento cuando tú corres. Dato de amor.", en: ""),
        .init(es: "Corre aunque no tengas ruta. La ruta aparece corriendo.", en: ""),
        .init(es: "Sal. Tu cerebro te lo pedirá con o sin palabras.", en: ""),
        .init(es: "Cada run es una conversación entre tú y tu cuerpo.", en: ""),
        .init(es: "El kilómetro de hoy vale más que el maratón de mañana.", en: ""),
        .init(es: "Corre aunque estés cansado. Especialmente si estás cansado.", en: ""),
        .init(es: "Tu mascota corre contigo en espíritu. Literalmente.", en: ""),
        .init(es: "Hoy no es viernes. Ni sábado. Ni festivo. Sal.", en: ""),
        .init(es: "El run que no hiciste ayer te está esperando hoy.", en: ""),
        .init(es: "Tus zapatillas tienen kilómetros pendientes. No las enamores del closet.", en: ""),
        .init(es: "Sal a correr. El sol salió primero para darte el ejemplo.", en: ""),
        .init(es: "Cada paso es una votación por quién quieres ser.", en: ""),
        .init(es: "Corre. La versión de ti que no lo hizo ya perdió.", en: ""),
        .init(es: "Tu mascota tiene buena memoria. Los kms cuentan.", en: ""),
        .init(es: "No necesitas correr lejos para llegar a algún lugar.", en: ""),
        .init(es: "El run de 10 minutos también es un run. No te hagas.", en: ""),
        .init(es: "Hoy tienes dos opciones. La que te hace bien gana.", en: ""),
        .init(es: "Sal. Las excusas se oxidan más rápido que los tenis.", en: ""),
        .init(es: "Correr no requiere talento, requiere zapatos y salida.", en: ""),
        .init(es: "El kilómetro que más importa es el próximo.", en: ""),
        .init(es: "Corre aunque el cielo esté nublado. Tus pulmones no le importa.", en: ""),
        .init(es: "Hoy no corres contra nadie. Solo contra tu excusa de ayer.", en: ""),
        .init(es: "Tu mascota no mide distancias. Mide intención.", en: ""),
        .init(es: "Sal. Tu cuerpo lleva días esperando que le hagas caso.", en: ""),
        .init(es: "Corre. Porque el movimiento es el lenguaje de los vivos.", en: ""),
        .init(es: "No necesitas música. No necesitas ruta. Solo necesitas salir.", en: ""),
        .init(es: "Cada run te acerca un paso a quien quieres ser.", en: ""),
        .init(es: "Hoy el sillón no gana. Tú sí.", en: ""),
        .init(es: "Corre. La versión más fuerte de ti ya está calentando.", en: ""),
        .init(es: "Tu mascota sabe cuándo corriste. Y cuándo no.", en: ""),
        .init(es: "Sal antes de que el día decida por ti.", en: ""),
        .init(es: "El run de hoy no es opcional. Los otros 65 días lo necesitan.", en: ""),
    ]
    // swiftlint:enable line_length
}
