import Foundation

struct RunningPhrase {
    let es: String
    let en: String  // TODO: fill when localizing to English
}

extension RunningPhrase {
    // swiftlint:disable line_length
    static let all: [RunningPhrase] = [
        .init(es: "Sal a correr. Tus excusas ya están en forma, tú no.", en: ""),
        .init(es: "La cama no te va a extrañar tanto como crees.", en: ""),
        .init(es: "Tus tenis están polvorientos. Eso dice todo.", en: ""),
        .init(es: "Correr duele. Quedarse quieto para siempre también.", en: ""),
        .init(es: "Un km. Ni siquiera tu abuela lo discutiría.", en: ""),
        .init(es: "Tu yo de mañana va a odiarte menos si sales hoy.", en: ""),
        .init(es: "Vitamina D: viene en kilómetros, no en cápsulas.", en: ""),
        .init(es: "Cada paso cuenta. Incluso el que diste al refri.", en: ""),
        .init(es: "El sofá te quiere. Tus arterias, no tanto.", en: ""),
        .init(es: "Correr es gratis. El cardiólogo, no.", en: ""),
        .init(es: "Hoy es un buen día para no arrepentirte mañana.", en: ""),
        .init(es: "Tu mascota necesita energía. Tú necesitas menos excusas.", en: ""),
        .init(es: "Nadie se arrepintió de un día que salió a correr.", en: ""),
        .init(es: "El clima nunca va a ser perfecto. Sal de todas formas.", en: ""),
        .init(es: "Corre lento si quieres, pero corre.", en: ""),
        .init(es: "Tu cuerpo puede más de lo que tu cabeza admite.", en: ""),
        .init(es: "El peor run es el que no hiciste.", en: ""),
        .init(es: "Sal afuera. Netflix sigue ahí cuando regreses.", en: ""),
        .init(es: "Correr 1km quema vergüenza y calorías, en ese orden.", en: ""),
        .init(es: "Tus músculos no crecen en el sillón. Dato curioso.", en: ""),
        .init(es: "El tiempo pasa igual corras o no. Mejor corriendo.", en: ""),
        .init(es: "No necesitas motivación, necesitas tenis y la puerta.", en: ""),
        .init(es: "Hoy es el 'mañana' que postergaste ayer.", en: ""),
        .init(es: "El sudor es solo grasa llorando. Dale más razones.", en: ""),
        .init(es: "Sal a correr antes de que tu cerebro invente más excusas.", en: ""),
        .init(es: "Un run malo sigue siendo mejor que ningún run.", en: ""),
        .init(es: "Tu mascota corre contigo. Literalmente. No la defraudes.", en: ""),
        .init(es: "Cada km es una apuesta a tu yo de 10 años.", en: ""),
        .init(es: "Hoy decides: sillón o tenis.", en: ""),
        .init(es: "El oxígeno extra también le hace bien a tus ideas.", en: ""),
        .init(es: "Los tenis no se van a poner solos. Esperemos que no.", en: ""),
        .init(es: "Dale play a tu playlist y para de pensar.", en: ""),
        .init(es: "La ciudad se ve diferente desde las piernas.", en: ""),
        .init(es: "Tu mascota te mira. No la decepciones.", en: ""),
        .init(es: "El run más difícil es el primer paso fuera de la puerta.", en: ""),
        .init(es: "Hoy no es día de descanso si ayer tampoco corriste.", en: ""),
        .init(es: "La motivación viene después de empezar, no antes.", en: ""),
        .init(es: "Corre suficiente para que el helado de después valga.", en: ""),
        .init(es: "Afuera hay aire fresco. Adentro hay pretextos.", en: ""),
        .init(es: "Si corriste, ganaste. Así de simple.", en: ""),
        .init(es: "Tu corazón quiere latir fuerte por las razones correctas.", en: ""),
        .init(es: "1km es 1km más que ayer. Matemáticas brutales.", en: ""),
        .init(es: "Tus rodillas ahorita: quejándose. En 10 años: agradecidas.", en: ""),
        .init(es: "Sal a correr. La ansiedad prefiere cuerpos quietos.", en: ""),
        .init(es: "Corre antes de que el día te gane la partida.", en: ""),
        .init(es: "No necesitas correr rápido, necesitas correr.", en: ""),
        .init(es: "Tu mascota tiene más energía cuando tú corres. Nota mental.", en: ""),
        .init(es: "El mundo no se acaba, pero tu día sí. Sal.", en: ""),
        .init(es: "Cada kilómetro le dice a tu cuerpo: todavía puedo.", en: ""),
        .init(es: "Tus excusas son muy creativas. Tus piernas también pueden.", en: ""),
        .init(es: "Corre despacio si quieres. El ritmo es tuyo, los km también.", en: ""),
        .init(es: "Los 66 días no se hacen solos. Empieza con uno.", en: ""),
        .init(es: "Hoy es día 1. O día 23. O 47. Sal de todas formas.", en: ""),
        .init(es: "Los audífonos y los tenis son el par perfecto.", en: ""),
        .init(es: "Hay un run ahí afuera con tu nombre. Ve por él.", en: ""),
        .init(es: "Tu mascota no te juzga el ritmo. Solo quiere que salgas.", en: ""),
        .init(es: "Corre. Porque estar vivo merece celebrarse en kilómetros.", en: ""),
        .init(es: "Tus pulmones mejoran usándolos. Como casi todo.", en: ""),
        .init(es: "El sol salió antes que tú. No lo hagas quedar mal.", en: ""),
        .init(es: "Un run = un día de orgullo. Las cuentas dan.", en: ""),
        .init(es: "Tu cuerpo quiere moverse. Tu cerebro tiene miedo al esfuerzo.", en: ""),
        .init(es: "La pereza es temporal. El hábito es para siempre.", en: ""),
        .init(es: "La mejor versión de ti ya está poniéndose los tenis.", en: ""),
        .init(es: "Corre aunque no quieras. Especialmente si no quieres.", en: ""),
        .init(es: "El kilómetro más honesto es siempre el primero.", en: ""),
        .init(es: "Afuera hace frío. Adentro hace cómodo. Sal de todas formas.", en: ""),
        .init(es: "Tu mascota se alegra cada vez que corres. No es coincidencia.", en: ""),
        .init(es: "Correr es lo más barato que puedes hacer por tu salud.", en: ""),
        .init(es: "No se trata de velocidad, se trata de aparecer.", en: ""),
        .init(es: "El asfalto está esperando tus pasos. O tus excusas. Tú decides.", en: ""),
        .init(es: "Cada run malo construye el run bueno que sigue.", en: ""),
        .init(es: "Tus pies saben el camino. Tu cabeza solo pone obstáculos.", en: ""),
        .init(es: "El run perfecto no existe. El run de hoy, sí.", en: ""),
        .init(es: "Correr es el único deporte donde siempre ganas contra ti.", en: ""),
        .init(es: "Hoy no es el día de echarte para atrás.", en: ""),
        .init(es: "Tus tenis no están decorando tu cuarto. Están esperando.", en: ""),
        .init(es: "Tu mente necesita kilómetros más que café. A veces.", en: ""),
        .init(es: "Un run al día mantiene la queja al margen.", en: ""),
        .init(es: "Corre aunque solo sea para contarlo después.", en: ""),
        .init(es: "El mejor momento para correr fue ayer. El segundo es ahora.", en: ""),
        .init(es: "Tu mascota cuenta cada km. No la hagas esperar.", en: ""),
        .init(es: "No mañana. Hoy. Ahora. Ya. ¿Qué estás esperando?", en: ""),
        .init(es: "Sal. Tu versión sedentaria no tiene voto en esto.", en: ""),
        .init(es: "Corre. Porque las endorfinas son felicidad de farmacia, gratis.", en: ""),
        .init(es: "El gym puede esperar. El hábito de 66 días, no tanto.", en: ""),
        .init(es: "Incluso los lentos llegan. Un km a la vez.", en: ""),
        .init(es: "Sal. Tu yo del futuro ya tiene los tenis puestos.", en: ""),
        .init(es: "Corre. Tus problemas no pueden alcanzarte... bueno, pero sudas.", en: ""),
        .init(es: "La cama es cómoda. También lo es rendirse. Piénsalo.", en: ""),
        .init(es: "Tu colesterol no se baja viendo el partido. Dato.", en: ""),
        .init(es: "Sal. Hay endorfinas ahí afuera y son completamente legales.", en: ""),
        .init(es: "Corre. Porque sí. Porque puedes. Porque ¿por qué no?", en: ""),
        .init(es: "Hoy no es el día de negociar con tu sillón.", en: ""),
        .init(es: "Los 66 días se construyen uno a la vez. Este es el tuyo.", en: ""),
        .init(es: "Sal afuera. Tu mascota ya tiene las patas listas.", en: ""),
        .init(es: "Corre. Tu corazón te lo va a agradecer. Tu Netflix, no.", en: ""),
        .init(es: "El run de hoy es la energía de mañana. Y pasado.", en: ""),
        .init(es: "Sal. La ciudad tiene un camino con tu nombre grabado.", en: ""),
        .init(es: "Corre aunque la playlist no esté en su mejor canción.", en: ""),
    ]
    // swiftlint:enable line_length
}
