import Foundation

struct RunningPhrase {
    let es: String
    let en: String  // TODO: fill when localizing to English

    var localized: String {
        let lang = Locale.current.language.languageCode?.identifier ?? "es"
        return lang == "en" && !en.isEmpty ? en : es
    }
}

extension RunningPhrase {
    // swiftlint:disable line_length
    static let all: [RunningPhrase] = [
        .init(es: "Sal a correr. Tus excusas ya están en forma, tú no.", en: "Go for a run. Your excuses are in great shape — you're not."),
        .init(es: "La cama no te va a extrañar tanto como crees.", en: "Your bed won't miss you as much as you think."),
        .init(es: "Tus tenis están polvorientos. Eso dice todo.", en: "Your sneakers are dusty. That says it all."),
        .init(es: "Correr duele. Quedarse quieto para siempre también.", en: "Running hurts. Staying still forever hurts more."),
        .init(es: "Un km. Ni siquiera tu abuela lo discutiría.", en: "One km. Even your grandma wouldn't argue with that."),
        .init(es: "Tu yo de mañana va a odiarte menos si sales hoy.", en: "Tomorrow-you will hate you less if you go out today."),
        .init(es: "Vitamina D: viene en kilómetros, no en cápsulas.", en: "Vitamin D: measured in kilometers, not capsules."),
        .init(es: "Cada paso cuenta. Incluso el que diste al refri.", en: "Every step counts. Even the one to the fridge."),
        .init(es: "El sofá te quiere. Tus arterias, no tanto.", en: "The couch loves you. Your arteries? Not so much."),
        .init(es: "Correr es gratis. El cardiólogo, no.", en: "Running is free. The cardiologist isn't."),
        .init(es: "Hoy es un buen día para no arrepentirte mañana.", en: "Today is a great day to not regret tomorrow."),
        .init(es: "Tu pacepal necesita energía. Tú necesitas menos excusas.", en: "Your pacepal needs energy. You need fewer excuses."),
        .init(es: "Nadie se arrepintió de un día que salió a correr.", en: "Nobody ever regretted a day they went for a run."),
        .init(es: "El clima nunca va a ser perfecto. Sal de todas formas.", en: "The weather will never be perfect. Go anyway."),
        .init(es: "Corre lento si quieres, pero corre.", en: "Run slow if you want, but run."),
        .init(es: "Tu cuerpo puede más de lo que tu cabeza admite.", en: "Your body can do more than your brain admits."),
        .init(es: "El peor run es el que no hiciste.", en: "The worst run is the one you didn't do."),
        .init(es: "Sal afuera. Netflix sigue ahí cuando regreses.", en: "Go outside. Netflix will still be there when you get back."),
        .init(es: "Correr 1km quema vergüenza y calorías, en ese orden.", en: "Running 1km burns shame and calories — in that order."),
        .init(es: "Tus músculos no crecen en el sillón. Dato curioso.", en: "Your muscles don't grow on the couch. Fun fact."),
        .init(es: "El tiempo pasa igual corras o no. Mejor corriendo.", en: "Time passes whether you run or not. Better running."),
        .init(es: "No necesitas motivación, necesitas tenis y la puerta.", en: "You don't need motivation — you need sneakers and the door."),
        .init(es: "Hoy es el 'mañana' que postergaste ayer.", en: "Today is the 'tomorrow' you put off yesterday."),
        .init(es: "El sudor es solo grasa llorando. Dale más razones.", en: "Sweat is just fat crying. Give it more reasons."),
        .init(es: "Sal a correr antes de que tu cerebro invente más excusas.", en: "Go run before your brain invents more excuses."),
        .init(es: "Un run malo sigue siendo mejor que ningún run.", en: "A bad run is still better than no run."),
        .init(es: "Tu pacepal corre contigo. Literalmente. No lo defraudes.", en: "Your pacepal runs with you. Literally. Don't let it down."),
        .init(es: "Cada km es una apuesta a tu yo de 10 años.", en: "Every km is a bet on the you 10 years from now."),
        .init(es: "Hoy decides: sillón o tenis.", en: "Today you decide: couch or sneakers."),
        .init(es: "El oxígeno extra también le hace bien a tus ideas.", en: "Extra oxygen is good for your ideas too."),
        .init(es: "Los tenis no se van a poner solos. Esperemos que no.", en: "Your sneakers won't lace themselves. Let's hope not."),
        .init(es: "Dale play a tu playlist y para de pensar.", en: "Hit play on your playlist and stop thinking."),
        .init(es: "La ciudad se ve diferente desde las piernas.", en: "The city looks different from your legs."),
        .init(es: "Tu pacepal te mira. No lo decepciones.", en: "Your pacepal is watching. Don't disappoint it."),
        .init(es: "El run más difícil es el primer paso fuera de la puerta.", en: "The hardest run is the first step out the door."),
        .init(es: "Hoy no es día de descanso si ayer tampoco corriste.", en: "Today isn't rest day if yesterday wasn't run day either."),
        .init(es: "La motivación viene después de empezar, no antes.", en: "Motivation comes after you start, not before."),
        .init(es: "Corre suficiente para que el helado de después valga.", en: "Run enough to earn that ice cream afterwards."),
        .init(es: "Afuera hay aire fresco. Adentro hay pretextos.", en: "Outside there's fresh air. Inside there's excuses."),
        .init(es: "Si corriste, ganaste. Así de simple.", en: "If you ran, you won. Simple as that."),
        .init(es: "Tu corazón quiere latir fuerte por las razones correctas.", en: "Your heart wants to beat hard for the right reasons."),
        .init(es: "1km es 1km más que ayer. Matemáticas brutales.", en: "1km is 1km more than yesterday. Brutal math."),
        .init(es: "Tus rodillas ahorita: quejándose. En 10 años: agradecidas.", en: "Your knees now: complaining. In 10 years: grateful."),
        .init(es: "Sal a correr. La ansiedad prefiere cuerpos quietos.", en: "Go for a run. Anxiety prefers still bodies."),
        .init(es: "Corre antes de que el día te gane la partida.", en: "Run before the day beats you to it."),
        .init(es: "No necesitas correr rápido, necesitas correr.", en: "You don't need to run fast — you need to run."),
        .init(es: "Tu pacepal tiene más energía cuando tú corres. Nota mental.", en: "Your pacepal has more energy when you run. Mental note."),
        .init(es: "El mundo no se acaba, pero tu día sí. Sal.", en: "The world isn't ending, but your day is. Go."),
        .init(es: "Cada kilómetro le dice a tu cuerpo: todavía puedo.", en: "Every kilometer tells your body: I've still got it."),
        .init(es: "Tus excusas son muy creativas. Tus piernas también pueden.", en: "Your excuses are very creative. Your legs can be too."),
        .init(es: "Corre despacio si quieres. El ritmo es tuyo, los km también.", en: "Run slow if you want. The pace is yours, so are the kms."),
        .init(es: "Los 66 días no se hacen solos. Empieza con uno.", en: "The 66 days don't happen on their own. Start with one."),
        .init(es: "Hoy es día 1. O día 23. O 47. Sal de todas formas.", en: "Today is day 1. Or day 23. Or 47. Go anyway."),
        .init(es: "Los audífonos y los tenis son el par perfecto.", en: "Headphones and sneakers are the perfect pair."),
        .init(es: "Hay un run ahí afuera con tu nombre. Ve por él.", en: "There's a run out there with your name on it. Go get it."),
        .init(es: "Tu pacepal no te juzga el ritmo. Solo quiere que salgas.", en: "Your pacepal doesn't judge your pace. It just wants you out."),
        .init(es: "Corre. Porque estar vivo merece celebrarse en kilómetros.", en: "Run. Because being alive deserves to be celebrated in kilometers."),
        .init(es: "Tus pulmones mejoran usándolos. Como casi todo.", en: "Your lungs improve with use. Like most things."),
        .init(es: "El sol salió antes que tú. No lo hagas quedar mal.", en: "The sun got up before you. Don't make it look bad."),
        .init(es: "Un run = un día de orgullo. Las cuentas dan.", en: "One run = one day of pride. The math checks out."),
        .init(es: "Tu cuerpo quiere moverse. Tu cerebro tiene miedo al esfuerzo.", en: "Your body wants to move. Your brain is scared of effort."),
        .init(es: "La pereza es temporal. El hábito es para siempre.", en: "Laziness is temporary. The habit is forever."),
        .init(es: "La mejor versión de ti ya está poniéndose los tenis.", en: "The best version of you is already lacing up."),
        .init(es: "Corre aunque no quieras. Especialmente si no quieres.", en: "Run even if you don't want to. Especially then."),
        .init(es: "El kilómetro más honesto es siempre el primero.", en: "The most honest kilometer is always the first."),
        .init(es: "Afuera hace frío. Adentro hace cómodo. Sal de todas formas.", en: "It's cold outside. It's cozy inside. Go anyway."),
        .init(es: "Tu pacepal se alegra cada vez que corres. No es coincidencia.", en: "Your pacepal lights up every time you run. Not a coincidence."),
        .init(es: "Correr es lo más barato que puedes hacer por tu salud.", en: "Running is the cheapest thing you can do for your health."),
        .init(es: "No se trata de velocidad, se trata de aparecer.", en: "It's not about speed — it's about showing up."),
        .init(es: "El asfalto está esperando tus pasos. O tus excusas. Tú decides.", en: "The pavement is waiting for your steps. Or your excuses. You pick."),
        .init(es: "Cada run malo construye el run bueno que sigue.", en: "Every bad run builds the good run that follows."),
        .init(es: "Tus pies saben el camino. Tu cabeza solo pone obstáculos.", en: "Your feet know the way. Your head just puts up roadblocks."),
        .init(es: "El run perfecto no existe. El run de hoy, sí.", en: "The perfect run doesn't exist. Today's run does."),
        .init(es: "Correr es el único deporte donde siempre ganas contra ti.", en: "Running is the only sport where you always win against yourself."),
        .init(es: "Hoy no es el día de echarte para atrás.", en: "Today is not the day to back down."),
        .init(es: "Tus tenis no están decorando tu cuarto. Están esperando.", en: "Your sneakers aren't decorating your room. They're waiting."),
        .init(es: "Tu mente necesita kilómetros más que café. A veces.", en: "Your mind needs kilometers more than coffee. Sometimes."),
        .init(es: "Un run al día mantiene la queja al margen.", en: "A run a day keeps the complaints away."),
        .init(es: "Corre aunque solo sea para contarlo después.", en: "Run if only to brag about it later."),
        .init(es: "El mejor momento para correr fue ayer. El segundo es ahora.", en: "The best time to run was yesterday. The second best is now."),
        .init(es: "Tu pacepal cuenta cada km. No lo hagas esperar.", en: "Your pacepal counts every km. Don't keep it waiting."),
        .init(es: "No mañana. Hoy. Ahora. Ya. ¿Qué estás esperando?", en: "Not tomorrow. Today. Now. Go. What are you waiting for?"),
        .init(es: "Sal. Tu versión sedentaria no tiene voto en esto.", en: "Go. Your sedentary self doesn't get a vote on this."),
        .init(es: "Corre. Porque las endorfinas son felicidad de farmacia, gratis.", en: "Run. Because endorphins are pharmacy-grade happiness, for free."),
        .init(es: "El gym puede esperar. El hábito de 66 días, no tanto.", en: "The gym can wait. The 66-day habit? Not so much."),
        .init(es: "Incluso los lentos llegan. Un km a la vez.", en: "Even the slow ones finish. One km at a time."),
        .init(es: "Sal. Tu yo del futuro ya tiene los tenis puestos.", en: "Go. Future-you already has their sneakers on."),
        .init(es: "Corre. Tus problemas no pueden alcanzarte... bueno, pero sudas.", en: "Run. Your problems can't catch you... well, but you'll sweat."),
        .init(es: "La cama es cómoda. También lo es rendirse. Piénsalo.", en: "Bed is comfy. So is quitting. Think about it."),
        .init(es: "Tu colesterol no se baja viendo el partido. Dato.", en: "Your cholesterol won't drop from watching the game. Fact."),
        .init(es: "Sal. Hay endorfinas ahí afuera y son completamente legales.", en: "Go. There are endorphins out there and they're completely legal."),
        .init(es: "Corre. Porque sí. Porque puedes. Porque ¿por qué no?", en: "Run. Because yes. Because you can. Because why not?"),
        .init(es: "Hoy no es el día de negociar con tu sillón.", en: "Today is not the day to negotiate with your couch."),
        .init(es: "Los 66 días se construyen uno a la vez. Este es el tuyo.", en: "The 66 days are built one at a time. This one is yours."),
        .init(es: "Sal afuera. Tu pacepal ya tiene las patas listas.", en: "Get outside. Your pacepal already has its paws ready."),
        .init(es: "Corre. Tu corazón te lo va a agradecer. Tu Netflix, no.", en: "Run. Your heart will thank you. Your Netflix won't."),
        .init(es: "El run de hoy es la energía de mañana. Y pasado.", en: "Today's run is tomorrow's energy. And the day after."),
        .init(es: "Sal. La ciudad tiene un camino con tu nombre grabado.", en: "Go. The city has a path with your name on it."),
        .init(es: "Corre aunque la playlist no esté en su mejor canción.", en: "Run even if your playlist isn't on its best song."),
        .init(es: "Hoy no te pido un maratón. Solo que salgas.", en: "I'm not asking for a marathon. Just get out the door."),
        .init(es: "El hábito que buscas está del otro lado de la puerta.", en: "The habit you're after is on the other side of the door."),
        .init(es: "Tu cuerpo ya sabe cómo correr. Tu cerebro solo exagera.", en: "Your body already knows how to run. Your brain just overthinks it."),
        .init(es: "Dale a tus pulmones algo de qué presumir.", en: "Give your lungs something to brag about."),
        .init(es: "La versión floja de ti también quiere salir. No le hagas caso.", en: "The lazy version of you wants a say too. Ignore it."),
        .init(es: "Tus piernas tienen más kilómetros disponibles. Úsalos.", en: "Your legs have more kilometers available. Use them."),
        .init(es: "El piso no se va a mover solo. Muévete tú.", en: "The ground isn't going to move itself. You move."),
        .init(es: "Nadie en la historia lamentó haberse levantado a correr.", en: "Nobody in history regretted getting up to run."),
        .init(es: "Hoy tu pacepal tiene hambre de kilómetros. Aliméntalo.", en: "Today your pacepal is hungry for kilometers. Feed it."),
        .init(es: "El viento en la cara no cuesta nada. Sal a sentirlo.", en: "Wind in your face costs nothing. Go feel it."),
        .init(es: "Correr es el único momento del día donde nadie te molesta.", en: "Running is the only time of day nobody bothers you."),
        .init(es: "Tu mente se reinicia con kilómetros, no con pantallas.", en: "Your mind reboots with kilometers, not screens."),
        .init(es: "Mueve el cuerpo antes de que el día te mueva a ti.", en: "Move your body before the day moves you."),
        .init(es: "Hay un run esperándote. Puntual, calladito, sin excusas.", en: "There's a run waiting for you. On time, quiet, no excuses."),
        .init(es: "Sal aunque no estés de humor. El humor llega al segundo km.", en: "Go even if you're not in the mood. The mood kicks in at km two."),
        .init(es: "El mundo se ve más pequeño desde las piernas cansadas.", en: "The world looks smaller from tired legs."),
        .init(es: "Tu corazón late gratis. Hazlo latir por algo.", en: "Your heart beats for free. Make it beat for something."),
        .init(es: "No hace falta correr lejos. Solo hace falta correr.", en: "You don't have to run far. You just have to run."),
        .init(es: "Hoy el sofá pierde. Sal.", en: "Today the couch loses. Go."),
        .init(es: "Una vuelta a la manzana también es un run. Te cuento.", en: "A lap around the block is still a run. Just so you know."),
        .init(es: "El camino más corto al bienestar lleva tenis.", en: "The shortest path to wellness involves sneakers."),
        .init(es: "Si esperas que llueva para no salir, se llama excusa disfrazada.", en: "If you're waiting for rain to skip your run, that's an excuse in disguise."),
        .init(es: "Tu pacepal no tiene días malos cuando corren juntos.", en: "Your pacepal never has bad days when you run together."),
        .init(es: "Corre. Tu cerebro lo necesita más de lo que admite.", en: "Run. Your brain needs it more than it admits."),
        .init(es: "Hoy es el día que cambia el contador. Sal.", en: "Today is the day the counter changes. Go."),
        .init(es: "Tus pies tienen memoria. Enséñales el camino correcto.", en: "Your feet have memory. Teach them the right path."),
        .init(es: "La queja no quema calorías. El run sí.", en: "Complaining doesn't burn calories. Running does."),
        .init(es: "No se trata de ser rápido. Se trata de no parar.", en: "It's not about being fast. It's about not stopping."),
        .init(es: "El dolor de correr dura horas. El orgullo, días.", en: "The pain of running lasts hours. The pride lasts days."),
        .init(es: "Sal. La ciudad te tiene preparada una ruta sin cobrar.", en: "Go. The city has a route ready for you — free of charge."),
        .init(es: "Tu cuerpo es el único vehículo que no puedes cambiar. Mantenlo.", en: "Your body is the only vehicle you can't trade in. Maintain it."),
        .init(es: "Corre antes de que el desayuno tome partido por el sillón.", en: "Run before breakfast sides with the couch."),
        .init(es: "Los 66 días te necesitan a ti, no al gimnasio.", en: "The 66 days need you, not a gym."),
        .init(es: "Cinco minutos trotando ya cambiaron tu día. Pruébalo.", en: "Five minutes jogging already changed your day. Try it."),
        .init(es: "Tu pacepal no entiende de descanso activo. Solo de correr.", en: "Your pacepal doesn't understand active rest. Only running."),
        .init(es: "Hoy no. Claro que no. Pero sal de todas formas.", en: "Not today. Of course not. But go anyway."),
        .init(es: "El sudor es el idioma que hablan tus metas.", en: "Sweat is the language your goals speak."),
        .init(es: "No necesitas estar listo. Necesitas estar afuera.", en: "You don't need to be ready. You need to be outside."),
        .init(es: "Hay un km ahí afuera que ya tiene tu nombre. Reclámalo.", en: "There's a km out there with your name on it. Claim it."),
        .init(es: "Tu mood mejora con movimiento. Dato no tan curioso.", en: "Your mood improves with movement. Not exactly breaking news."),
        .init(es: "Corre por las razones incorrectas si quieres. Igual cuenta.", en: "Run for the wrong reasons if you want. It still counts."),
        .init(es: "El mejor run es el que nadie más puede hacer por ti.", en: "The best run is the one nobody else can do for you."),
        .init(es: "Sal. Tu versión sedentaria ya habló bastante hoy.", en: "Go. Your sedentary self has talked enough today."),
        .init(es: "Un solo run puede salvar un día completo. Intento probado.", en: "A single run can save an entire day. Proven method."),
        .init(es: "El mundo tiene kilómetros gratis. No los desperdicies.", en: "The world has free kilometers. Don't waste them."),
        .init(es: "Tu pacepal lleva la cuenta. Hoy le debes uno.", en: "Your pacepal keeps count. Today you owe it one."),
        .init(es: "Sal aunque solo sean 15 minutos. El hábito no negocia.", en: "Go even if it's just 15 minutes. The habit doesn't negotiate."),
        .init(es: "Tus arterias se merecen un poco de esfuerzo hoy.", en: "Your arteries deserve a little effort today."),
        .init(es: "El run que menos ganas tienes es el que más necesitas.", en: "The run you least want is the one you need most."),
        .init(es: "Corre. Después puedes comer lo que quieras. Más o menos.", en: "Run. Then you can eat whatever you want. More or less."),
        .init(es: "El asfalto no juzga tu ritmo. Solo tus pies.", en: "The pavement doesn't judge your pace. Only your feet."),
        .init(es: "Hoy es uno de los 66. No lo desperdicies.", en: "Today is one of the 66. Don't waste it."),
        .init(es: "Tu energía no se agota corriendo, se multiplica.", en: "Your energy doesn't drain from running — it multiplies."),
        .init(es: "Corre aunque tu cuerpo diga que no. Especialmente entonces.", en: "Run even when your body says no. Especially then."),
        .init(es: "El tiempo pasa igual. Mejor que te encuentre en movimiento.", en: "Time passes either way. Better it finds you moving."),
        .init(es: "No hay run perfecto. Hay run de hoy. Ese alcanza.", en: "There's no perfect run. There's today's run. That's enough."),
        .init(es: "Sal. Tu pacepal ya se puso los tenis imaginarios.", en: "Go. Your pacepal already put on its imaginary sneakers."),
        .init(es: "Un run malo te pone en mejor forma que ningún run.", en: "A bad run puts you in better shape than no run."),
        .init(es: "Hoy no tienes excusa nueva. Ya las usaste todas.", en: "You're out of new excuses today. You've used them all."),
        .init(es: "Tus pulmones ensanchan con uso. No guardes el empaque.", en: "Your lungs expand with use. Don't leave them in the packaging."),
        .init(es: "El primer km siempre miente. Después se pone bueno.", en: "The first km always lies. It gets good after that."),
        .init(es: "Sal a que el aire te limpie la cabeza.", en: "Go let the air clear your head."),
        .init(es: "Tu cuerpo es el proyecto más importante que tienes.", en: "Your body is the most important project you have."),
        .init(es: "Corre para ti. No para la app. Pero la app también lo registra.", en: "Run for you. Not for the app. But the app tracks it too."),
        .init(es: "El mejor antidepresivo tiene cordones y suela de goma.", en: "The best antidepressant has laces and a rubber sole."),
        .init(es: "Hoy es el día 1 de alguien. Que sea el tuyo también.", en: "Today is someone's day 1. Make it yours too."),
        .init(es: "No necesitas un plan. Necesitas salir por la puerta.", en: "You don't need a plan. You need to walk out the door."),
        .init(es: "Tu pacepal envejece más lento cuando tú corres. Dato de amor.", en: "Your pacepal ages slower when you run. A love fact."),
        .init(es: "Corre aunque no tengas ruta. La ruta aparece corriendo.", en: "Run even without a route. The route shows up while running."),
        .init(es: "Sal. Tu cerebro te lo pedirá con o sin palabras.", en: "Go. Your brain will ask for it, with or without words."),
        .init(es: "Cada run es una conversación entre tú y tu cuerpo.", en: "Every run is a conversation between you and your body."),
        .init(es: "El kilómetro de hoy vale más que el maratón de mañana.", en: "Today's kilometer is worth more than tomorrow's marathon."),
        .init(es: "Corre aunque estés cansado. Especialmente si estás cansado.", en: "Run even if you're tired. Especially if you're tired."),
        .init(es: "Tu pacepal corre contigo en espíritu. Literalmente.", en: "Your pacepal runs with you in spirit. Literally."),
        .init(es: "Hoy no es viernes. Ni sábado. Ni festivo. Sal.", en: "Today isn't Friday. Or Saturday. Or a holiday. Go."),
        .init(es: "El run que no hiciste ayer te está esperando hoy.", en: "The run you skipped yesterday is waiting for you today."),
        .init(es: "Tus zapatillas tienen kilómetros pendientes. No las enamores del closet.", en: "Your shoes have pending kilometers. Don't let them fall in love with the closet."),
        .init(es: "Sal a correr. El sol salió primero para darte el ejemplo.", en: "Go for a run. The sun came out first to set the example."),
        .init(es: "Cada paso es una votación por quién quieres ser.", en: "Every step is a vote for who you want to be."),
        .init(es: "Corre. La versión de ti que no lo hizo ya perdió.", en: "Run. The version of you that didn't already lost."),
        .init(es: "Tu pacepal tiene buena memoria. Los kms cuentan.", en: "Your pacepal has a good memory. The kms count."),
        .init(es: "No necesitas correr lejos para llegar a algún lugar.", en: "You don't need to run far to get somewhere."),
        .init(es: "El run de 10 minutos también es un run. No te hagas.", en: "A 10-minute run is still a run. Don't kid yourself."),
        .init(es: "Hoy tienes dos opciones. La que te hace bien gana.", en: "Today you have two options. The one that's good for you wins."),
        .init(es: "Sal. Las excusas se oxidan más rápido que los tenis.", en: "Go. Excuses rust faster than sneakers."),
        .init(es: "Correr no requiere talento, requiere zapatos y salida.", en: "Running doesn't require talent — just shoes and a door."),
        .init(es: "El kilómetro que más importa es el próximo.", en: "The kilometer that matters most is the next one."),
        .init(es: "Corre aunque el cielo esté nublado. Tus pulmones no le importa.", en: "Run even if it's cloudy. Your lungs don't care."),
        .init(es: "Hoy no corres contra nadie. Solo contra tu excusa de ayer.", en: "Today you're not racing anyone. Just yesterday's excuse."),
        .init(es: "Tu pacepal no mide distancias. Mide intención.", en: "Your pacepal doesn't measure distance. It measures intention."),
        .init(es: "Sal. Tu cuerpo lleva días esperando que le hagas caso.", en: "Go. Your body has been waiting days for you to listen."),
        .init(es: "Corre. Porque el movimiento es el lenguaje de los vivos.", en: "Run. Because movement is the language of the living."),
        .init(es: "No necesitas música. No necesitas ruta. Solo necesitas salir.", en: "You don't need music. You don't need a route. Just get out."),
        .init(es: "Cada run te acerca un paso a quien quieres ser.", en: "Every run gets you one step closer to who you want to be."),
        .init(es: "Hoy el sillón no gana. Tú sí.", en: "Today the couch doesn't win. You do."),
        .init(es: "Corre. La versión más fuerte de ti ya está calentando.", en: "Run. The strongest version of you is already warming up."),
        .init(es: "Tu pacepal sabe cuándo corriste. Y cuándo no.", en: "Your pacepal knows when you ran. And when you didn't."),
        .init(es: "Sal antes de que el día decida por ti.", en: "Go before the day decides for you."),
        .init(es: "El run de hoy no es opcional. Los otros 65 días lo necesitan.", en: "Today's run isn't optional. The other 65 days need it."),
        // ── 100 frases nuevas ────────────────────────────────────────────────
        .init(es: "Tu pacepal no pide mucho. Solo que muevas las piernas.", en: "Your pacepal doesn't ask for much. Just move your legs."),
        .init(es: "El asfalto no cobra. La excusa, sí te cobra algo más caro.", en: "The pavement is free. Excuses cost you something way more expensive."),
        .init(es: "Sal. No para quemar calorías, sino para recordar que puedes.", en: "Go. Not to burn calories, but to remember you can."),
        .init(es: "Los 66 días no te piden velocidad. Te piden constancia.", en: "The 66 days don't ask for speed. They ask for consistency."),
        .init(es: "Cada kilómetro es silencio bien aprovechado.", en: "Every kilometer is silence well spent."),
        .init(es: "Tus zapatillas no son de adorno. Deja que lo demuestren.", en: "Your shoes aren't decoration. Let them prove it."),
        .init(es: "El run de hoy es la racha de mañana. No la rompas.", en: "Today's run is tomorrow's streak. Don't break it."),
        .init(es: "Tu pacepal festeja cada km como si fuera el primero.", en: "Your pacepal celebrates every km like it's the first."),
        .init(es: "Sal. Nadie te va a aplaudir desde el sillón.", en: "Go. Nobody's going to clap for you from the couch."),
        .init(es: "Corre aunque no hayas dormido bien. El cuerpo se ajusta.", en: "Run even if you slept badly. Your body adjusts."),
        .init(es: "Afuera está el km que necesitas. Aquí dentro, solo pretextos.", en: "The km you need is outside. In here, there's only excuses."),
        .init(es: "El hábito que buscas se construye corriendo, no pensando en correr.", en: "The habit you want is built by running, not thinking about running."),
        .init(es: "Hoy no tienes que ser el más rápido. Solo el que sí salió.", en: "You don't have to be the fastest today. Just the one who showed up."),
        .init(es: "Tu pacepal guarda cada paso. No le falles.", en: "Your pacepal saves every step. Don't let it down."),
        .init(es: "Corre. El mundo exterior siempre gana al interior.", en: "Run. The outside world always beats the indoors."),
        .init(es: "Cinco kilómetros o quinientos metros. Los dos son un sí.", en: "Five kilometers or five hundred meters. Both are a yes."),
        .init(es: "Tu mente tiene prioridades equivocadas. Corrígelas en movimiento.", en: "Your mind has its priorities wrong. Fix them in motion."),
        .init(es: "Hoy el run es terapia. Y sale más barato.", en: "Today the run is therapy. And it's way cheaper."),
        .init(es: "Sal. Tu pacepal lleva rato calentando sin ti.", en: "Go. Your pacepal has been warming up without you."),
        .init(es: "El hábito es la suma de muchos días que dijeron que sí.", en: "Habit is the sum of many days that said yes."),
        .init(es: "Tus piernas recuerdan cada kilómetro. Dales más razones.", en: "Your legs remember every kilometer. Give them more reasons."),
        .init(es: "El camino no pide disculpas por ser difícil. Tú tampoco.", en: "The road doesn't apologize for being hard. Neither should you."),
        .init(es: "Corre. Tu cerebro produce las mejores ideas en movimiento.", en: "Run. Your brain produces its best ideas in motion."),
        .init(es: "No hay atajos en los 66 días. Solo pasos hacia adelante.", en: "There are no shortcuts in the 66 days. Only steps forward."),
        .init(es: "Tu pacepal no conoce los lunes. Para él, todos los días son run.", en: "Your pacepal doesn't know Mondays. For it, every day is run day."),
        .init(es: "Sal. El clima es una excusa, no una razón.", en: "Go. The weather is an excuse, not a reason."),
        .init(es: "Cada run te dice algo que el sofá no puede.", en: "Every run tells you something the couch can't."),
        .init(es: "No busques el momento perfecto. El momento es ahora.", en: "Don't wait for the perfect moment. The moment is now."),
        .init(es: "Tu cuerpo tiene kilómetros de garantía sin usar. Úsalos.", en: "Your body has unused warranty kilometers. Use them."),
        .init(es: "Hoy sales y mañana lo agradeces. Ecuación simple.", en: "Go out today and be grateful tomorrow. Simple equation."),
        .init(es: "Tu pacepal tiene energía acumulada. Dale salida.", en: "Your pacepal has stored-up energy. Let it out."),
        .init(es: "Corre. No existe versión mejorada de ti que no lo haga.", en: "Run. There's no upgraded version of you that doesn't."),
        .init(es: "El run de hoy es el descanso que mereces mañana.", en: "Today's run is the rest you deserve tomorrow."),
        .init(es: "Sal aunque sea despacio. La tortuga también llegó.", en: "Go even if it's slow. The tortoise finished too."),
        .init(es: "Tu corazón tiene rebajas de calorías hoy. Aprovecha.", en: "Your heart has a calorie sale today. Take advantage."),
        .init(es: "Cada día que corres eres exactamente quien querías ser.", en: "Every day you run, you're exactly who you wanted to be."),
        .init(es: "Tu pacepal no entiende de 'mañana'. Solo de 'ahora'.", en: "Your pacepal doesn't understand 'tomorrow'. Only 'now'."),
        .init(es: "Sal. La calle está vacía y toda tuya.", en: "Go. The street is empty and all yours."),
        .init(es: "Un run sin récord igual es un run ganado.", en: "A run without a record is still a run won."),
        .init(es: "No necesitas fuerza extra. Solo necesitas dar el primer paso.", en: "You don't need extra strength. Just take the first step."),
        .init(es: "Tus pulmones saben la diferencia entre ayer y hoy. Cuéntales.", en: "Your lungs know the difference between yesterday and today. Show them."),
        .init(es: "El run de 20 minutos cambia el día completo. Matemáticas raras.", en: "A 20-minute run changes the whole day. Weird math."),
        .init(es: "Tu pacepal tiene hambre de pasos. Aliméntalo hoy.", en: "Your pacepal is hungry for steps. Feed it today."),
        .init(es: "Sal. No hay nada en casa que no pueda esperar 30 minutos.", en: "Go. Nothing at home can't wait 30 minutes."),
        .init(es: "Corre. Porque tu yo de los 40 te lo va a agradecer.", en: "Run. Because 40-year-old you will thank you."),
        .init(es: "El dolor muscular de mañana es el recuerdo de haber vivido hoy.", en: "Tomorrow's sore muscles are proof you lived today."),
        .init(es: "Un run a la semana no construye hábito. Sal más seguido.", en: "One run a week doesn't build a habit. Go more often."),
        .init(es: "Tu pacepal celebra cada salida como si fuera la primera.", en: "Your pacepal celebrates every outing like it's the first."),
        .init(es: "Sal aunque llueva. El agua no pesa tanto como el arrepentimiento.", en: "Go even if it rains. Water doesn't weigh as much as regret."),
        .init(es: "El km más difícil ya lo tienes adentro. Solo libéralo.", en: "The hardest km is already inside you. Just set it free."),
        .init(es: "Corre. Porque no hay app que sustituya al movimiento real.", en: "Run. Because no app replaces actual movement."),
        .init(es: "Hoy defines si eres de los que lo intentan o de los que lo hacen.", en: "Today you decide: are you someone who tries or someone who does?"),
        .init(es: "Tu pacepal te espera con más energía cada vez que corres.", en: "Your pacepal waits for you with more energy every time you run."),
        .init(es: "Sal. La ciudad tiene esquinas que todavía no conoces.", en: "Go. The city has corners you haven't discovered yet."),
        .init(es: "Correr no te hace más rápido, te hace más constante. Mejor aún.", en: "Running doesn't make you faster — it makes you more consistent. Even better."),
        .init(es: "El run de hoy no compite con el de ayer. Solo suma.", en: "Today's run doesn't compete with yesterday's. It just adds up."),
        .init(es: "Tus excusas tienen caducidad. Las de hoy ya vencieron.", en: "Your excuses have an expiration date. Today's already expired."),
        .init(es: "Tu pacepal vive de kilómetros. No lo dejes en ayunas.", en: "Your pacepal lives on kilometers. Don't starve it."),
        .init(es: "Sal. El regreso siempre se siente mejor que la salida.", en: "Go. Coming back always feels better than heading out."),
        .init(es: "Corre. Tu mente ordenada empieza en las piernas en movimiento.", en: "Run. A clear mind starts with legs in motion."),
        .init(es: "Hoy no necesitas correr bien. Solo necesitas correr.", en: "You don't need to run well today. You just need to run."),
        .init(es: "El paso más lento hacia adelante sigue siendo hacia adelante.", en: "The slowest step forward is still a step forward."),
        .init(es: "Tu pacepal no tiene días libres si tú no los tienes.", en: "Your pacepal doesn't get days off if you don't."),
        .init(es: "Sal. La calle no te va a juzgar el ritmo.", en: "Go. The street won't judge your pace."),
        .init(es: "Cada run es una promesa que te cumples a ti mismo.", en: "Every run is a promise you keep to yourself."),
        .init(es: "No te compares con nadie. Compárate con ayer.", en: "Don't compare yourself to anyone. Compare with yesterday."),
        .init(es: "Tu cuerpo fue diseñado para moverse. No para el escritorio.", en: "Your body was designed to move. Not for a desk."),
        .init(es: "Hoy es el día que tu pacepal más te necesita. Sal.", en: "Today is the day your pacepal needs you most. Go."),
        .init(es: "El run que pospones es el hábito que nunca llega.", en: "The run you postpone is the habit that never arrives."),
        .init(es: "Sal. Afuera hay aire, kilómetros y razones para estar bien.", en: "Go. Outside there's air, kilometers, and reasons to feel good."),
        .init(es: "Corre. Porque el movimiento hace lo que el silencio no puede.", en: "Run. Because movement does what silence can't."),
        .init(es: "Un km hoy vale más que diez que no existen.", en: "One km today is worth more than ten that don't exist."),
        .init(es: "Tu pacepal guarda memoria de cada esfuerzo. No lo borres.", en: "Your pacepal remembers every effort. Don't erase it."),
        .init(es: "Sal aunque solo puedas 10 minutos. 10 minutos cambian algo.", en: "Go even if you only have 10 minutes. 10 minutes change something."),
        .init(es: "El run no te pide que seas atleta. Solo que aparezcas.", en: "The run doesn't ask you to be an athlete. Just to show up."),
        .init(es: "Hoy no hay excusa que no hayas usado antes. Sal.", en: "There's no excuse today you haven't used before. Go."),
        .init(es: "Tu corazón tiene una velocidad favorita: la que logras corriendo.", en: "Your heart has a favorite speed: the one you hit while running."),
        .init(es: "Tu pacepal y tú son el mejor equipo que nadie ve.", en: "You and your pacepal are the best team nobody sees."),
        .init(es: "Sal. Lo que pesa no es el cuerpo, son las decisiones pendientes.", en: "Go. What weighs you down isn't your body — it's the decisions you keep putting off."),
        .init(es: "Correr afuera es la única pantalla que te hace bien.", en: "Running outside is the only screen that's good for you."),
        .init(es: "Hoy la meta no es lejos. Está justo del otro lado de la puerta.", en: "Today the finish line isn't far. It's right on the other side of the door."),
        .init(es: "El km que más cuesta es el que más vale.", en: "The km that costs the most is worth the most."),
        .init(es: "Tu pacepal tiene fe en ti aunque tú no la tengas hoy.", en: "Your pacepal believes in you even when you don't."),
        .init(es: "Sal. Tu cuerpo sabe más que tu cerebro cuando se trata de moverse.", en: "Go. Your body knows more than your brain when it comes to moving."),
        .init(es: "Corre. Los 66 días no son un reto, son una decisión.", en: "Run. The 66 days aren't a challenge — they're a decision."),
        .init(es: "No hay run pequeño. Hay run hecho y run que no.", en: "There's no small run. There's a run done and a run not done."),
        .init(es: "Tu energía se genera corriendo, no esperando tenerla.", en: "Your energy is generated by running, not by waiting for it."),
        .init(es: "Tu pacepal brilla más cuando tú corres. No es magia, es esfuerzo.", en: "Your pacepal shines brighter when you run. It's not magic — it's effort."),
        .init(es: "Sal. La ciudad amanece diferente desde los tenis.", en: "Go. The city looks different at dawn from your sneakers."),
        .init(es: "El run que no quieres hacer es exactamente el que necesitas.", en: "The run you don't want to do is exactly the one you need."),
        .init(es: "Hoy decides si el hábito te gana a ti o tú al hábito.", en: "Today you decide: does the habit beat you, or do you beat the habit?"),
        .init(es: "Corre. Después del km 1, el cuerpo toma el mando.", en: "Run. After km 1, your body takes over."),
        .init(es: "Tu pacepal no sabe rendirse. Aprende de él.", en: "Your pacepal doesn't know how to quit. Learn from it."),
        .init(es: "Sal. Las mejores ideas llegan corriendo, no sentado.", en: "Go. The best ideas come while running, not sitting."),
        .init(es: "Un run hoy es una racha mañana. No la dejes morir.", en: "A run today is a streak tomorrow. Don't let it die."),
        .init(es: "Correr solo o acompañado igual suma. Sal.", en: "Running solo or with someone — it all counts. Go."),
        .init(es: "Tu cuerpo tiene combustible. Las excusas consumen más.", en: "Your body has fuel. Excuses burn through more of it."),
        .init(es: "Tu pacepal solo pide que no te rindas hoy.", en: "Your pacepal only asks that you don't give up today."),
        .init(es: "Sal. El mundo exterior tiene más para ofrecerte que el techo.", en: "Go. The outside world has more to offer than your ceiling."),
        .init(es: "Hoy no te pido velocidad. Solo que muevas los pies.", en: "I'm not asking for speed today. Just move your feet."),
        .init(es: "El run de 66 días empieza con el run de hoy.", en: "The 66-day run starts with today's run."),
    ]
    // swiftlint:enable line_length
}
